devgateway/iatiimport

import-core/import-ui/src/main/webapp/client/i18n/translations.js, import-core/import-ui/src/main/webapp/client/mockup/menu_items_embedded.json
AMP-25770 IATI translation to Spanish
=> AMP-25770 IATI translation to Spanish

import-core/import-ui/src/main/resources/static/mockup/menu_items_embedded.json, import-core/import-ui/src/main/webapp/client/i18n/translations.js, import-core/import-ui/src/main/webapp/client/scripts/components/home.jsx, import-core/import-ui/src/main/webapp/client/scripts/components/reports/import-list.jsx, import-core/import-ui/src/main/webapp/client/scripts/components/reports/workflow-list.jsx, import-core/import-ui/src/main/webapp/client/scripts/components/wizard/choose-fields.jsx, import-core/import-ui/src/main/webapp/client/scripts/components/wizard/custom-select.jsx, import-core/import-ui/src/main/webapp/client/scripts/components/wizard/import-report.jsx, import-core/import-ui/src/main/webapp/client/scripts/components/wizard/index.jsx, import-core/import-ui/src/main/webapp/client/scripts/components/wizard/map-values-table-simple.jsx, import-core/import-ui/src/main/webapp/client/scripts/components/wizard/map-values-table.jsx, import-core/import-ui/src/main/webapp/client/scripts/components/wizard/map-values.jsx, import-core/import-ui/src/main/webapp/client/scripts/components/wizard/upload-file.jsx
AMP-25789 missing translations in iati import tool
=> AMP-25789 missing translations in iati import tool

import-core/import-ui/src/main/webapp/client/styles/main.css
AMP-25789 Translation issue - spanish text does not fit in button
=> AMP-25789 Translation issue - spanish text does not fit in button

import-core/import-ui/src/main/webapp/client/i18n/translations.js
=> AMP-26957 Add fr translations

import-core/import-rest/pom.xml, import-core/import-services/pom.xml, import-core/import-ui/pom.xml, import-core/pom.xml
AMP-27009 Increment version on develop to 0.0.13 after releasing v0.0.12
=> AMP-27009 Increment version on develop to 0.0.13 after releasing v0.0.12

import-core/import-rest/src/main/java/org/devgateway/importtool/rest/FieldMappingTemplateController.java, import-core/import-rest/src/main/java/org/devgateway/importtool/rest/ValueMappingTemplateController.java, import-core/import-ui/src/main/webapp/client/scripts/components/wizard/choose-fields.jsx, import-core/import-ui/src/main/webapp/client/scripts/components/wizard/map-values.jsx, import-core/import-ui/src/main/webapp/client/scripts/components/wizard/save-field-mappings-dlg.jsx, import-core/import-ui/src/main/webapp/client/scripts/components/wizard/save-value-mappings-dlg.jsx
Fix for saving mappings and value mappings for the first time
=> Fix for saving mappings and value mappings for the first time

import-core/import-ui/src/main/webapp/client/scripts/components/wizard/index.jsx
UNICIATI-32 reduced checking time from 5 seconds to 1
=> UNICIATI-32 reduced checking time from 5 seconds to 1

import-core/import-rest/src/main/java/org/devgateway/importtool/rest/DataController.java
=> UNICIATI-35 small bug

import-core/import-services/src/main/java/org/devgateway/importtool/services/processor/AMPStaticProcessor.java
UNICIATI-40 Fix - Description is not imported
=> UNICIATI-40 Fix - Description is not imported

import-core/import-rest/pom.xml, import-core/import-services/pom.xml, import-core/import-ui/pom.xml, import-core/pom.xml
Merge v0.0.17 pre release into master
=> Merge v0.0.17 pre release into master

import-core/import-services/src/main/java/org/devgateway/importtool/services/processor/AMPStaticProcessor.java
AMP-28004 IATI support / troubleshooting for AMP Workshop
=> AMP-28004 IATI support / troubleshooting for AMP Workshop

import-core/import-rest/pom.xml, import-core/import-services/pom.xml, import-core/import-ui/pom.xml, import-core/pom.xml
=> AMP-26701 Increment version

import-core/import-services/src/main/java/org/devgateway/importtool/services/processor/IATI1XProcessor.java, import-core/import-services/src/main/java/org/devgateway/importtool/services/processor/IATI2XProcessor.java
AMP-28062 Fix incorrect title issue - modify how title and description are extracted from iati file
=> AMP-28062 Fix incorrect title issue

import-core/import-services/src/main/java/org/devgateway/importtool/services/processor/helper/DocumentMapper.java
AMP-28067 Issue IATI: Override project title does not work
=> AMP-28067 Issue IATI: Override project title does not work

import-core/import-ui/src/main/webapp/client/scripts/components/wizard/save-field-mappings-dlg.jsx, import-core/import-ui/src/main/webapp/client/scripts/components/wizard/save-value-mappings-dlg.jsx
AMP-28072 it is possible to save template with empty name
=> AMP-28072 it is possible to save template with empty name

import-core/import-ui/src/main/webapp/client/scripts/components/wizard/choose-projects.jsx
AMP-28100 Autocomplete function not works on "destination project" field
=> AMP-28100 Autocomplete function not works on "destination project" field

import-core/import-ui/src/main/webapp/client/scripts/components/wizard/save-field-mappings-dlg.jsx, import-core/import-ui/src/main/webapp/client/scripts/components/wizard/save-value-mappings-dlg.jsx
AMP-28072 Fix issue - empty name
=> AMP-28072 Fix issue - empty name

import-core/import-services/src/main/java/org/devgateway/importtool/services/processor/AMPStaticProcessor.java
AMP-28071 Some fields are missing source values in mapping page
=> AMP-28071 Some fields are missing source values in mapping page

import-core/import-services/src/main/java/org/devgateway/importtool/services/processor/IATI1XProcessor.java, import-core/import-services/src/main/java/org/devgateway/importtool/services/processor/IATI2XProcessor.java, import-core/import-ui/src/main/webapp/client/scripts/components/wizard/choose-projects.jsx
IATIIMPORT-173 Haiti iati import> transaction, locations and other data preview and import issues
=> IATIIMPORT-173 Haiti iati import> transaction, locations and other data preview and import issues

import-core/import-services/src/main/java/org/devgateway/importtool/services/processor/AMPStaticProcessor.java
IATIIMPORT-172 Haiti iati import finished with Error:null
=> IATIIMPORT-172 Haiti iati import finished with Error:null

import-core/import-rest/src/main/java/org/devgateway/importtool/rest/FieldMappingTemplateController.java, import-core/import-rest/src/main/java/org/devgateway/importtool/rest/ValueMappingTemplateController.java, import-core/import-services/src/main/java/org/devgateway/importtool/dao/FieldMappingTemplateRepository.java, import-core/import-services/src/main/java/org/devgateway/importtool/dao/ValueMappingTemplateRepository.java, import-core/import-ui/src/main/webapp/client/scripts/components/wizard/save-field-mappings-dlg.jsx
IATIIMPORT-176 mapping templates are not being loaded
=> IATIIMPORT-176 mapping templates are not being loaded

import-core/import-ui/src/main/webapp/client/scripts/components/wizard/filter-data.jsx
IATIIMPORT-165 no language selector in FIlter information screen
=> IATIIMPORT-165 no language selector in FIlter information screen

import-core/import-services/src/main/java/org/devgateway/importtool/services/processor/AMPStaticProcessor.java
IATIIMPORT-158 multi-lingual text import issues
- import fails when title is shorter than 255 characters
- import fails if multi-lingual is enabled
=> IATIIMPORT-158 multi-lingual text import issues

import-core/import-services/src/main/java/org/devgateway/importtool/services/processor/AMPStaticProcessor.java, import-core/import-services/src/main/java/org/devgateway/importtool/services/processor/IATI1XProcessor.java, import-core/import-services/src/main/java/org/devgateway/importtool/services/processor/IATI2XProcessor.java, import-core/import-services/src/main/java/org/devgateway/importtool/services/processor/helper/Constants.java
IATIIMPORT-179 Organizations are not being imported
=> IATIIMPORT-179 Organizations are not being imported

import-core/import-services/src/main/java/org/devgateway/importtool/services/processor/AMPStaticProcessor.java, import-core/import-services/src/main/java/org/devgateway/importtool/services/processor/helper/FieldValue.java, import-core/import-ui/src/main/webapp/client/scripts/components/wizard/map-values-table-simple.jsx, import-core/import-ui/src/main/webapp/client/scripts/components/wizard/map-values.jsx
IATIIMPORT-221 Missing translations in map values step
=> IATIIMPORT-221 Missing translations in map values step

import-core/import-ui/src/main/webapp/client/i18n/translations.js
IATIIMPORT-220 Missing translations in import process popup
=> IATIIMPORT-220 Missing translations in import process popup

import-core/import-ui/src/main/webapp/client/scripts/utils/common.js, import-core/import-ui/src/main/webapp/client/scripts/utils/constants.js
IATIIMPORT-148 Show project title based on language priority en,fr,es
=> IATIIMPORT-148 Show project title based on language priority en,fr,es

import-core/import-services/src/main/java/org/devgateway/importtool/services/DataService.java, import-core/import-services/src/main/java/org/devgateway/importtool/services/processor/helper/DocumentMapper.java, import-core/import-services/src/main/java/org/devgateway/importtool/services/processor/helper/IDocumentMapper.java
IATIIMPORT-236 Only map values that are present in selected projects
=> IATIIMPORT-236 Only map values that are present in selected projects

import-core/import-ui/src/main/webapp/client/scripts/components/wizard/choose-projects.jsx
IATIIMPORT-256 iati cannot select projects from Update list
=> IATIIMPORT-256 iati cannot select projects from Update list

import-core/import-ui/src/main/webapp/client/scripts/components/wizard/autocomplete.jsx
IATIIMPORT-253 Make AMP sectors searchable without French accents
=> IATIIMPORT-253 Make AMP sectors searchable without French accents

import-core/import-services/src/main/java/org/devgateway/importtool/services/ImportService.java, import-core/import-services/src/main/java/org/devgateway/importtool/services/processor/AMPProcessor.java, import-core/import-services/src/main/java/org/devgateway/importtool/services/processor/AMPStaticProcessor.java, import-core/import-services/src/main/java/org/devgateway/importtool/services/processor/config/AmpStaticProcessorConfig.java, import-core/import-services/src/main/java/org/devgateway/importtool/services/processor/config/DestinationProcessorConfiguration.java, import-core/import-services/src/main/java/org/devgateway/importtool/services/processor/helper/Constants.java, import-core/import-services/src/main/java/org/devgateway/importtool/services/processor/helper/IDestinationProcessor.java, import-core/import-ui/src/main/resources/application.properties
implement is_draft and can download to draft. Also refactored how configuration are sent to the processor
=> IATIIMPORT-270 implement is_draft and can downgrade to draft.
